<a href="https://colab.research.google.com/github/Techdevweb/Auto_ML/blob/main/Auto_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import autosklearn

In [ ]:
#Regression 
import pandas as pd
df=pd.read_csv('housing.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [ ]:
target=df.pop('median_house_value')
df=pd.concat([df,target],axis=1) #Putting med_house at last
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0       322.0       126.0         8.3252        NEAR BAY            452600.0  
1      2401.0      1138.0         8.3014        NEAR BAY            358500.0  
2       496.0       177.0         7.2574        NEAR BAY            352100.0  
3       558.0       219.0         5.6431        NEAR BAY            341300.0  
4       565.0       259.0         3.8462        NEAR BAY            342200.0

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
ocean_proximity        object
median_house_value    float64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
df['ocean_proximity']=le.fit_transform(df['ocean_proximity'])
df #Data replacing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  ocean_proximity  \
0           322.0       126.0         8.3252                3   
1          2401.0      1138.0         8.3014                3   
2           496.0       177.0         7.2574                3   
3           558.0       219.0         5.6431                3   
4           565.0       259.0         3.8462                3   
...           ...         ...            ...              ...   
20635       845.0       330.0         1.5603                1   
20636       356.0       114.0         2.5568                1   
20637      1007.0       433.0         1.7000                1   
20638       741.0       349.0         1.8672                1   
20639      1387.0       530.0         2.3886                1   

       median_house_value  
0                452600.0  
1                358500.0  
2                352100.0  
3                341300.0  
4                342200.0  
...                   ...  
20635             78100.0  
20636             77100.0  
20637             92300.0  
20638             84700.0  
20639             89400.0  

[20640 rows x 10 columns]

In [ ]:
df=df.sample(frac=1,random_state=0)
df.reset_index(drop=True,inplace=True)
split_index=int(len(df)*0.75)

In [ ]:
train_df=df[:split_index]
test_df=df[split_index:]

In [ ]:
train_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -117.05     32.58                22.0       2101.0           399.0   
1        -117.97     33.92                32.0       2620.0           398.0   
2        -121.84     38.65                29.0       3167.0           548.0   
3        -115.60     33.20                37.0        709.0           187.0   
4        -122.43     37.79                25.0       1637.0           394.0   
...          ...       ...                 ...          ...             ...   
15475    -120.05     36.97                20.0       2029.0           427.0   
15476    -118.24     34.08                52.0        109.0            20.0   
15477    -118.29     33.84                33.0        896.0           208.0   
15478    -120.62     37.37                 8.0       2608.0           428.0   
15479    -121.11     37.47                12.0       2263.0           410.0   

       population  households  median_income  ocean_proximity  \
0          1551.0       371.0         4.1518                4   
1          1296.0       429.0         5.7796                0   
2          1554.0       534.0         4.3487                1   
3           390.0       142.0         2.4511                1   
4           649.0       379.0         5.0049                3   
...           ...         ...            ...              ...   
15475       983.0       401.0         1.8444                1   
15476        86.0        24.0         4.9844                0   
15477       843.0       200.0         3.5000                0   
15478      1530.0       435.0         3.9680                1   
15479       913.0       330.0         3.5795                1   

       median_house_value  
0                136900.0  
1                241300.0  
2                200700.0  
3                 72500.0  
4                460000.0  
...                   ...  
15475             47100.0  
15476            187500.0  
15477            183000.0  
15478            102100.0  
15479            145600.0  

[15480 rows x 10 columns]

In [ ]:
X_train = train_df.to_numpy()[:, :-1]
y_train = train_df.to_numpy()[:, -1]

X_test = test_df.to_numpy()[:, :-1]
y_test = test_df.to_numpy()[:, -1]
#Converting data types to numpy

(X_train.shape, y_train.shape), (X_test.shape, y_test.shape)

(((15480, 9), (15480,)), ((5160, 9), (5160,)))

In [ ]:
feature_types = ['Numerical']*8 + ['Categorical']

feature_types#Only for categorical encoding

['Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Categorical']

In [ ]:
import autosklearn.regression

autosklearn_regressor = autosklearn.regression.AutoSklearnRegressor(
    time_left_for_this_task=240,
    per_run_time_limit=60,
)

autosklearn_regressor.fit(X_train, y_train, feat_type=feature_types)#Implementing auto-sklearn

Process ForkProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autosklearn/util/logging_.py", line 320, in start_log_server
    receiver.serve_until_stopped()
  File "/usr/local/lib/python3.7/dist-packages/autosklearn/util/logging_.py", line 352, in serve_until_stopped
    self.timeout)
KeyboardInterrupt


AutoSklearnRegressor(per_run_time_limit=60, time_left_for_this_task=240)

In [ ]:
print(autosklearn_regressor.leaderboard())#Estimating best model

          rank  ensemble_weight               type      cost   duration
model_id                                                               
7            1             0.48  gradient_boosting  0.170498   6.150278
5            2             0.40  gradient_boosting  0.174482  50.833305
8            3             0.12  gradient_boosting  0.183270   4.445436


In [ ]:
from sklearn.metrics import mean_absolute_error as mae

mae(y_train, autosklearn_regressor.predict(X_train)), mae(y_test, autosklearn_regressor.predict(X_test))#Calculating mean square error

(19403.078443502578, 29948.53599569631)

In [ ]:
result=autosklearn_regressor.predict(X_train)
result#Implementing model

array([132986.7265625 , 249791.4609375 , 174758.18164062, ...,
       180512.04101562, 115060.83398438, 147645.59375   ])

In [ ]:
#Classification 

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()

X2, y2 = iris.data, iris.target

X2.shape, y2.shape

((150, 4), (150,))

In [ ]:
y2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.4, random_state=1)

X_train2.shape, y_train2.shape, X_test2.shape, y_test2.shape

((90, 4), (90,), (60, 4), (60,))

In [ ]:
#Implementing auto-sklearn for classification
import autosklearn.classification

autosklearn_classifier = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=80,
    per_run_time_limit=20,
)

autosklearn_classifier.fit(X_train2, y_train2) 

[WARNING] [2022-09-16 04:41:11,503:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2022-09-16 04:41:19,916:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2022-09-16 04:41:26,498:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.


AutoSklearnClassifier(per_run_time_limit=20, time_left_for_this_task=80)

In [ ]:
print(autosklearn_classifier.leaderboard()) #Printing best model

          rank  ensemble_weight                type      cost  duration
model_id                                                               
2            1             0.06       random_forest  0.000000  1.803274
25           2             0.04       random_forest  0.000000  2.171096
24           3             0.08   gradient_boosting  0.000000  1.635364
21           4             0.06         extra_trees  0.000000  1.841163
19           5             0.06       random_forest  0.000000  1.842576
12           6             0.06                 mlp  0.000000  2.126686
10           7             0.02                 mlp  0.000000  1.641446
14           8             0.02       random_forest  0.000000  1.772156
6            9             0.04          libsvm_svc  0.000000  0.894353
9           10             0.02       random_forest  0.000000  2.155312
16          11             0.04            adaboost  0.033333  1.879427
17          12             0.06   gradient_boosting  0.033333  1

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test2,autosklearn_classifier.predict(X_test2)))#Classification results

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.95      0.95      0.95        21
           2       0.95      0.95      0.95        20

    accuracy                           0.97        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.97      0.97      0.97        60



In [ ]:
autosklearn_classifier.predict(X_test2)#Predicting values

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1])